<?php
/**
 * GEMBOK Simple Installer
 * Wizard-based installer for easy hosting deployment
 */

session_start();

// Installer steps
$steps = [
    1 => ['name' => 'Server Check', 'file' => 'step1_server.php'],
    2 => ['name' => 'Database Setup', 'file' => 'step2_database.php'],
    3 => ['name' => 'Admin Setup', 'file' => 'step3_admin.php'],
    4 => ['name' => 'MikroTik Setup', 'file' => 'step4_mikrotik.php'],
    5 => ['name' => 'Integrations', 'file' => 'step5_integrations.php'],
    6 => ['name' => 'Finish', 'file' => 'step6_finish.php']
];

// Get current step
$currentStep = $_GET['step'] ?? 1;
$currentStep = max(1, min(6, (int)$currentStep));

// Check if already installed
if (file_exists('includes/config.php') && file_exists('includes/installed.lock')) {
    $installed = true;
} else {
    $installed = false;
}

// Prevent re-installation via POST if already installed
if ($installed && $_SERVER['REQUEST_METHOD'] === 'POST') {
    die("Application is already installed. Please remove includes/installed.lock if you want to reinstall.");
}

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($currentStep === 2) {
        // Save database config
        $_SESSION['db_config'] = [
            'host' => $_POST['db_host'],
            'name' => $_POST['db_name'],
            'user' => $_POST['db_user'],
            'pass' => $_POST['db_pass']
        ];
        
        // Test connection
        try {
            $pdo = new PDO(
                "mysql:host={$_POST['db_host']};dbname={$_POST['db_name']}",
                $_POST['db_user'],
                $_POST['db_pass']
            );
            $_SESSION['db_connected'] = true;
            header("Location: install.php?step=3");
            exit;
        } catch (PDOException $e) {
            $error = "Koneksi database gagal: " . $e->getMessage();
        }
    }
    
    if ($currentStep === 3) {
        // Save admin config
        $_SESSION['admin_config'] = [
            'username' => $_POST['admin_username'],
            'password' => password_hash($_POST['admin_password'], PASSWORD_DEFAULT),
            'email' => $_POST['admin_email']
        ];
        header("Location: install.php?step=4");
        exit;
    }
    
    if ($currentStep === 4) {
        // Save MikroTik config
        $_SESSION['mikrotik_config'] = [
            'host' => $_POST['mikrotik_host'],
            'user' => $_POST['mikrotik_user'],
            'pass' => $_POST['mikrotik_pass'],
            'port' => $_POST['mikrotik_port']
        ];
        header("Location: install.php?step=5");
        exit;
    }
    
    if ($currentStep === 5) {
        // Save integrations config
        $_SESSION['integrations_config'] = [
            'whatsapp_url' => $_POST['whatsapp_url'] ?? '',
            'whatsapp_token' => $_POST['whatsapp_token'] ?? '',
            'tripay_api_key' => $_POST['tripay_api_key'] ?? '',
            'tripay_private_key' => $_POST['tripay_private_key'] ?? '',
            'tripay_merchant_code' => $_POST['tripay_merchant_code'] ?? '',
            'telegram_token' => $_POST['telegram_token'] ?? ''
        ];
        header("Location: install.php?step=6");
        exit;
    }
    
    if ($currentStep === 6) {
        // Final installation
        installApplication();
    }
}

function installApplication() {
    global $error;
    try {
        // Create config.php
        $configContent = createConfigFile();
        if (file_put_contents('includes/config.php', $configContent) === false) {
            throw new Exception('Gagal menulis includes/config.php. Cek permission folder includes.');
        }
        
        // Create database tables
        createDatabaseTables();
        
        // Insert default data
        insertDefaultData();
        
        // Create installed.lock
        if (file_put_contents('includes/installed.lock', date('Y-m-d H:i:s')) === false) {
            throw new Exception('Gagal membuat includes/installed.lock. Cek permission folder includes.');
        }
        
        // Clear session
        unset($_SESSION['db_config']);
        unset($_SESSION['admin_config']);
        unset($_SESSION['mikrotik_config']);
        unset($_SESSION['integrations_config']);
        
        // Redirect to login
        header("Location: admin/login.php");
        exit;
    } catch (Exception $e) {
        $error = "Installation failed: " . $e->getMessage();
    }
}

function createConfigFile() {
    $db = $_SESSION['db_config'];
    $admin = $_SESSION['admin_config'];
    $mikrotik = $_SESSION['mikrotik_config'];
    $integrations = $_SESSION['integrations_config'];
    
    return <<<PHP
<?php
/**
 * GEMBOK Configuration File
 * Generated by installer on: {date('Y-m-d H:i:s')}
 */

// Database Configuration
define('DB_HOST', '{$db['host']}');
define('DB_NAME', '{$db['name']}');
define('DB_USER', '{$db['user']}');
define('DB_PASS', '{$db['pass']}');

// MikroTik Configuration
define('MIKROTIK_HOST', '{$mikrotik['host']}');
define('MIKROTIK_USER', '{$mikrotik['user']}');
define('MIKROTIK_PASS', '{$mikrotik['pass']}');
define('MIKROTIK_PORT', {$mikrotik['port']});

// Application Configuration
define('APP_NAME', 'GEMBOK');
if (php_sapi_name() !== 'cli' && isset(\$_SERVER['HTTP_HOST'])) {
    \$protocol = (!empty(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    \$scriptDir = str_replace('\\\\', '/', dirname(\$_SERVER['SCRIPT_NAME']));
    \$scriptDir = preg_replace('#/(admin|api|portal|cron|webhooks|install_steps|includes)$#', '', \$scriptDir);
    \$scriptDir = rtrim(\$scriptDir, '/');
    define('APP_URL', \$protocol . '://' . \$_SERVER['HTTP_HOST'] . \$scriptDir);
} else {
    define('APP_URL', 'http://localhost/gembok-simple2');
}
define('APP_VERSION', '2.0.5');
define('GEMBOK_UPDATE_VERSION_URL', 'https://raw.githubusercontent.com/alijaya0601/gembok-simple2/main/version.txt');

// Pagination and currency
define('ITEMS_PER_PAGE', 20);
define('CURRENCY', 'IDR');
define('CURRENCY_SYMBOL', 'Rp');
define('INVOICE_PREFIX', 'INV');
define('INVOICE_START', 1);

// Security
define('ENCRYPTION_KEY', bin2hex(random_bytes(32)));

// WhatsApp Configuration
define('WHATSAPP_API_URL', '{$integrations['whatsapp_url']}');
define('WHATSAPP_TOKEN', '{$integrations['whatsapp_token']}');

// Tripay Configuration
define('TRIPAY_API_KEY', '{$integrations['tripay_api_key']}');
define('TRIPAY_PRIVATE_KEY', '{$integrations['tripay_private_key']}');
define('TRIPAY_MERCHANT_CODE', '{$integrations['tripay_merchant_code']}');

// Telegram Configuration
define('TELEGRAM_BOT_TOKEN', '{$integrations['telegram_token']}');

// GenieACS Configuration
define('GENIEACS_URL', 'http://localhost:7557');
define('GENIEACS_USERNAME', '');
define('GENIEACS_PASSWORD', '');
PHP;
}

function createDatabaseTables() {
    require_once 'includes/db.php';

    $pdo = getDB();
    $payloadType = 'JSON';
    $version = '';
    try {
        $version = (string)$pdo->query("SELECT VERSION()")->fetchColumn();
    } catch (Exception $e) {
        $version = '';
    }
    if ($version !== '') {
        $versionNumber = preg_replace('/[^0-9.].*/', '', $version);
        if ($versionNumber !== '') {
            if (stripos($version, 'mariadb') !== false) {
                $payloadType = version_compare($versionNumber, '10.2.7', '>=') ? 'JSON' : 'LONGTEXT';
            } else {
                $payloadType = version_compare($versionNumber, '5.7.8', '>=') ? 'JSON' : 'LONGTEXT';
            }
        }
    }

    $sql = "
    CREATE TABLE IF NOT EXISTS settings (
        id INT AUTO_INCREMENT PRIMARY KEY,
        setting_key VARCHAR(100) UNIQUE,
        setting_value TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS admin_users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        email VARCHAR(100),
        name VARCHAR(100),
        reset_token VARCHAR(64),
        reset_expiry DATETIME,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS packages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        price DECIMAL(10,2) NOT NULL,
        profile_normal VARCHAR(50) NOT NULL,
        profile_isolir VARCHAR(50) NOT NULL,
        description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS customers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        phone VARCHAR(20),
        pppoe_username VARCHAR(50) UNIQUE NOT NULL,
        package_id INT,
        router_id INT DEFAULT 0,
        status ENUM('active', 'isolated') DEFAULT 'active',
        isolation_date INT DEFAULT 20,
        address TEXT,
        lat DECIMAL(10,8),
        lng DECIMAL(10,8),
        portal_password VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS invoices (
        id INT AUTO_INCREMENT PRIMARY KEY,
        invoice_number VARCHAR(50) UNIQUE NOT NULL,
        customer_id INT NOT NULL,
        amount DECIMAL(10,2) NOT NULL,
        status ENUM('unpaid', 'paid', 'cancelled') DEFAULT 'unpaid',
        due_date DATE NOT NULL,
        paid_at DATETIME,
        payment_method VARCHAR(50),
        payment_ref VARCHAR(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS odps (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        code VARCHAR(50) UNIQUE,
        lat DECIMAL(10,8),
        lng DECIMAL(10,8),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS onu_locations (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        serial_number VARCHAR(100) UNIQUE,
        lat DECIMAL(10,8),
        lng DECIMAL(10,8),
        odp_id INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (odp_id) REFERENCES odps(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS odp_links (
        id INT AUTO_INCREMENT PRIMARY KEY,
        from_odp_id INT NOT NULL,
        to_odp_id INT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (from_odp_id) REFERENCES odps(id) ON DELETE CASCADE,
        FOREIGN KEY (to_odp_id) REFERENCES odps(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS trouble_tickets (
        id INT AUTO_INCREMENT PRIMARY KEY,
        customer_id INT,
        description TEXT,
        status ENUM('pending', 'in_progress', 'resolved') DEFAULT 'pending',
        priority ENUM('low', 'medium', 'high') DEFAULT 'medium',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS cron_schedules (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        task_type VARCHAR(50),
        schedule_time TIME,
        schedule_days VARCHAR(20),
        is_active BOOLEAN DEFAULT 1,
        last_run DATETIME,
        next_run DATETIME,
        last_status VARCHAR(20),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS cron_logs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        schedule_id INT,
        status ENUM('success', 'failed', 'started'),
        output TEXT,
        error_message TEXT,
        execution_time FLOAT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (schedule_id) REFERENCES cron_schedules(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    CREATE TABLE IF NOT EXISTS webhook_logs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        source VARCHAR(50),
        payload {$payloadType},
        status_code INT,
        response TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    CREATE TABLE IF NOT EXISTS routers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        host VARCHAR(100) NOT NULL,
        username VARCHAR(100) NOT NULL,
        password VARCHAR(100) NOT NULL,
        port INT DEFAULT 8728,
        is_active BOOLEAN DEFAULT 0,
        description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    CREATE TABLE IF NOT EXISTS sales_users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        phone VARCHAR(20),
        username VARCHAR(50) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        deposit_balance DECIMAL(15,2) DEFAULT 0,
        status ENUM('active', 'inactive') DEFAULT 'active',
        voucher_mode VARCHAR(20) DEFAULT 'mix',
        voucher_length INT DEFAULT 6,
        voucher_type VARCHAR(20) DEFAULT 'upp',
        bill_discount DECIMAL(15,2) DEFAULT 2000,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    CREATE TABLE IF NOT EXISTS sales_transactions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        sales_user_id INT NOT NULL,
        type VARCHAR(50) NOT NULL,
        amount DECIMAL(15,2) NOT NULL,
        description TEXT,
        related_username VARCHAR(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (sales_user_id) REFERENCES sales_users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    CREATE TABLE IF NOT EXISTS sales_profile_prices (
        id INT AUTO_INCREMENT PRIMARY KEY,
        sales_user_id INT NOT NULL,
        profile_name VARCHAR(100) NOT NULL,
        base_price DECIMAL(15,2) NOT NULL DEFAULT 0,
        selling_price DECIMAL(15,2) NOT NULL DEFAULT 0,
        voucher_length INT DEFAULT 6,
        is_active BOOLEAN DEFAULT 1,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (sales_user_id) REFERENCES sales_users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    CREATE TABLE IF NOT EXISTS hotspot_sales (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(100),
        profile VARCHAR(100),
        price DECIMAL(15,2),
        selling_price DECIMAL(15,2),
        prefix VARCHAR(20),
        sales_user_id INT DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (sales_user_id) REFERENCES sales_users(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    CREATE TABLE IF NOT EXISTS site_settings (
        id INT AUTO_INCREMENT PRIMARY KEY,
        setting_key VARCHAR(50) UNIQUE NOT NULL,
        setting_value TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ";
    
    $statements = array_filter(array_map('trim', explode(';', $sql)));
    foreach ($statements as $statement) {
        if ($statement !== '') {
            $pdo->exec($statement);
        }
    }
}

function insertDefaultData() {
    require_once 'includes/db.php';
    
    $pdo = getDB();
    
    $admin = $_SESSION['admin_config'];
    $stmt = $pdo->prepare("INSERT IGNORE INTO admin_users (username, password, email, created_at) VALUES (?, ?, ?, NOW())");
    $stmt->execute([$admin['username'], $admin['password'], $admin['email']]);
    
    $settings = [
        ['app_name', 'GEMBOK'],
        ['app_version', '2.0.0'],
        ['currency', 'IDR'],
        ['timezone', 'Asia/Jakarta'],
        ['invoice_prefix', 'INV'],
        ['invoice_start', '1']
    ];
    
    foreach ($settings as $setting) {
        $stmt = $pdo->prepare("INSERT IGNORE INTO settings (setting_key, setting_value) VALUES (?, ?)");
        $stmt->execute($setting);
    }

    $siteSettings = [
        ['hero_title', 'Internet Cepat <br>Tanpa Batas'],
        ['hero_description', 'Nikmati koneksi internet fiber optic super cepat, stabil, dan unlimited untuk kebutuhan rumah maupun bisnis Anda. Gabung sekarang!'],
        ['contact_phone', '+62 812-3456-7890'],
        ['contact_email', 'info@gembok.net'],
        ['contact_address', 'Jakarta, Indonesia'],
        ['footer_about', 'Penyedia layanan internet terpercaya dengan jaringan fiber optic berkualitas untuk menunjang aktivitas digital Anda.'],
        ['feature_1_title', 'Kecepatan Tinggi'],
        ['feature_1_desc', 'Koneksi fiber optic dengan kecepatan simetris upload dan download.'],
        ['feature_2_title', 'Unlimited Quota'],
        ['feature_2_desc', 'Akses internet sepuasnya tanpa batasan kuota (FUP).'],
        ['feature_3_title', 'Support 24/7'],
        ['feature_3_desc', 'Tim teknis kami siap membantu Anda kapanpun jika terjadi gangguan.'],
        ['social_facebook', '#'],
        ['social_instagram', '#'],
        ['social_twitter', '#'],
        ['social_youtube', '#']
    ];

    foreach ($siteSettings as $ss) {
        $stmt = $pdo->prepare("INSERT IGNORE INTO site_settings (setting_key, setting_value) VALUES (?, ?)");
        $stmt->execute($ss);
    }

    $cronSchedules = [
        ['Auto Invoice', 'auto_invoice', 'monthly', '00:00', 1],
        ['Auto Isolir', 'auto_isolir', 'daily', '00:00', 1],
        ['Payment Reminder', 'send_reminders', 'daily', '08:00', 1]
    ];
    
    foreach ($cronSchedules as $schedule) {
        $stmt = $pdo->prepare("INSERT IGNORE INTO cron_schedules (name, task_type, schedule_days, schedule_time, is_active) VALUES (?, ?, ?, ?, ?)");
        $stmt->execute($schedule);
    }
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GEMBOK Installer</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Inter', system-ui, sans-serif;
            background: radial-gradient(circle at center, #1a1a2e 0%, #0a0a12 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
            color: #ffffff;
        }
        .container {
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            max-width: 800px;
            width: 100%;
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }
        .header h1 { font-size: 2.5rem; margin-bottom: 10px; }
        .header p { opacity: 0.9; }
        .progress {
            display: flex;
            justify-content: space-between;
            padding: 20px 40px;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
        }
        .step {
            flex: 1;
            text-align: center;
            padding: 10px;
            font-size: 0.9rem;
            color: #6c757d;
            position: relative;
        }
        .step.active { color: #667eea; font-weight: 600; }
        .step.completed { color: #28a745; }
        .step::after {
            content: '';
            position: absolute;
            bottom: 0;
            left: 50%;
            transform: translateX(-50%);
            width: 0;
            height: 3px;
            background: #667eea;
            transition: width 0.3s;
        }
        .step.active::after, .step.completed::after { width: 100%; }
        .content {
            padding: 40px;
        }
        .form-group { margin-bottom: 20px; }
        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #333;
        }
        .form-group input, .form-group select, .form-group textarea {
            width: 100%;
            padding: 12px;
            border: 2px solid #e9ecef;
            border-radius: 8px;
            font-size: 1rem;
            transition: border-color 0.3s;
        }
        .form-group input:focus, .form-group select:focus {
            outline: none;
            border-color: #667eea;
        }
        .btn {
            padding: 12px 30px;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
        }
        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(102, 126, 234, 0.3);
        }
        .btn-secondary {
            background: #6c757d;
            color: white;
        }
        .alert {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .alert-error { background: #fee; border: 1px solid #fcc; color: #c33; }
        .alert-success { background: #efe; border: 1px solid #cfc; color: #3c3; }
        .alert-info { background: #eef; border: 1px solid #ccf; color: #33c; }
        .check-item {
            display: flex;
            align-items: center;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 8px;
            margin-bottom: 10px;
        }
        .check-item i {
            font-size: 1.5rem;
            margin-right: 15px;
        }
        .check-item.success i { color: #28a745; }
        .check-item.error i { color: #dc3545; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚀 GEMBOK Installer</h1>
            <p>ISP Management System - Simple Version</p>
        </div>
        
        <div class="progress">
            <?php foreach ($steps as $num => $step): ?>
                <div class="step <?php echo $num == $currentStep ? 'active' : ($num < $currentStep ? 'completed' : ''); ?>">
                    <?php echo $num . '. ' . $step['name']; ?>
                </div>
            <?php endforeach; ?>
        </div>
        
        <div class="content">
            <?php if ($installed): ?>
                <div class="alert alert-success">
                    <h3>✅ Sudah Terinstall!</h3>
                    <p>Aplikasi GEMBOK sudah terinstall di server ini.</p>
                    <p>Silakan <a href="admin/login.php">Login ke Admin Panel</a></p>
                </div>
            <?php else: ?>
                <?php if (isset($error)): ?>
                    <div class="alert alert-error">
                        <strong>Error:</strong> <?php echo htmlspecialchars($error); ?>
                    </div>
                <?php endif; ?>
                
                <?php
                switch ($currentStep) {
                    case 1: include 'install_steps/step1_server.php'; break;
                    case 2: include 'install_steps/step2_database.php'; break;
                    case 3: include 'install_steps/step3_admin.php'; break;
                    case 4: include 'install_steps/step4_mikrotik.php'; break;
                    case 5: include 'install_steps/step5_integrations.php'; break;
                    case 6: include 'install_steps/step6_finish.php'; break;
                }
                ?>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
