<?php
/**
 * GEMBOK Configuration File
 * Generated by installer on: {date('Y-m-d H:i:s')}
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'gembok_simple');
define('DB_USER', 'root');
define('DB_PASS', '');

// MikroTik Configuration
define('MIKROTIK_HOST', '192.168.8.1');
define('MIKROTIK_USER', 'alijaya');
define('MIKROTIK_PASS', '060111');
define('MIKROTIK_PORT', 8700);

// Application Configuration
define('APP_NAME', 'GEMBOK');
$appScheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
define('APP_URL', $appScheme . '://' . $_SERVER['HTTP_HOST']);
define('APP_VERSION', '2.0.0');
define('GEMBOK_UPDATE_VERSION_URL', 'https://raw.githubusercontent.com/alijayanet/gembok-simple/main/version.txt');

// Security
define('ENCRYPTION_KEY', bin2hex(random_bytes(32)));

// WhatsApp Configuration
define('WHATSAPP_API_URL', '');
define('WHATSAPP_TOKEN', '');
define('FONNTE_API_TOKEN', '');
define('WABLAS_API_TOKEN', '');
define('MPWA_API_KEY', '');

// Tripay Configuration
define('TRIPAY_API_KEY', '');
define('TRIPAY_PRIVATE_KEY', '');
define('TRIPAY_MERCHANT_CODE', '');

// Telegram Configuration
define('TELEGRAM_BOT_TOKEN', '');

// GenieACS Configuration
define('GENIEACS_URL', 'http://192.168.8.89:7557');
define('GENIEACS_USERNAME', '');
define('GENIEACS_PASSWORD', '');

// Timezone
date_default_timezone_set('Asia/Jakarta');

// Error Reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Session Configuration
ini_set('session.cookie_httponly', 1);
ini_set('session.use_only_cookies', 1);
ini_set('session.cookie_secure', 0); // Set to 1 if using HTTPS
define('SESSION_TIMEOUT', 3600); // 1 hour

// Check session timeout
if (isset($_SESSION['admin']['login_time'])) {
    if (time() - $_SESSION['admin']['login_time'] > SESSION_TIMEOUT) {
        session_destroy();
        header('Location: ' . APP_URL . '/admin/login.php');
        exit;
    }
}

if (isset($_SESSION['customer']['login_time'])) {
    if (time() - $_SESSION['customer']['login_time'] > SESSION_TIMEOUT) {
        session_destroy();
        header('Location: ' . APP_URL . '/portal/login.php');
        exit;
    }
}

// File Upload
define('UPLOAD_MAX_SIZE', 5242880); // 5MB
define('UPLOAD_ALLOWED_TYPES', ['jpg', 'jpeg', 'png', 'pdf']);

// Pagination
if (!defined('ITEMS_PER_PAGE')) {
    define('ITEMS_PER_PAGE', 20);
}

// Currency
if (!defined('CURRENCY')) {
    define('CURRENCY', 'IDR');
}
if (!defined('CURRENCY_SYMBOL')) {
    define('CURRENCY_SYMBOL', 'Rp');
}

// Invoice Settings
define('INVOICE_PREFIX', 'INV');
define('INVOICE_START', 1);
