<?php
/**
 * GEMBOK Configuration File
 * Generated by installer on: {date('Y-m-d H:i:s')}
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'gembok_simple2');
define('DB_USER', 'root');
define('DB_PASS', '');

// MikroTik Configuration
define('MIKROTIK_HOST', '192.168.8.1');
define('MIKROTIK_USER', 'alijaya');
define('MIKROTIK_PASS', '060111');
define('MIKROTIK_PORT', 8700);

// Application Configuration
define('APP_NAME', 'GEMBOK');
if (php_sapi_name() !== 'cli' && isset($_SERVER['HTTP_HOST'])) {
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    // Base directory detection
    $scriptDir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME']));
    
    // Clean up known subdirectories to find root
    $dirsToRemove = ['/admin', '/api', '/portal', '/cron', '/webhooks', '/install_steps', '/includes', '/sales', '/templates'];
    
    foreach ($dirsToRemove as $dir) {
        if (strpos($scriptDir, $dir) !== false) {
            $scriptDir = str_replace($dir, '', $scriptDir);
        }
    }
    
    $scriptDir = rtrim($scriptDir, '/');
    define('APP_URL', $protocol . '://' . $_SERVER['HTTP_HOST'] . $scriptDir);
} else {
    define('APP_URL', 'http://localhost/gembok-simple2');
}
define('APP_VERSION', '2.0.5');
define('GEMBOK_UPDATE_VERSION_URL', 'https://raw.githubusercontent.com/alijaya0601/gembok-simple2/main/version.txt');

// Pagination and currency
define('ITEMS_PER_PAGE', 20);
define('CURRENCY', 'IDR');
define('CURRENCY_SYMBOL', 'Rp');
define('INVOICE_PREFIX', 'INV');
define('INVOICE_START', 1);

// Security
define('ENCRYPTION_KEY', bin2hex(random_bytes(32)));

// WhatsApp Configuration
define('WHATSAPP_API_URL', '');
define('WHATSAPP_TOKEN', '');

// Tripay Configuration
define('TRIPAY_API_KEY', '');
define('TRIPAY_PRIVATE_KEY', '');
define('TRIPAY_MERCHANT_CODE', '');

// Telegram Configuration
define('TELEGRAM_BOT_TOKEN', '');

// GenieACS Configuration
define('GENIEACS_URL', 'http://localhost:7557');
define('GENIEACS_USERNAME', '');
define('GENIEACS_PASSWORD', '');